name: "Language Manager"

on:
  push:
    branches: dev
    paths:
      - translations/*.po
  pull_request:
    branches:
      - "dev" 
    paths:
      - ".github/workflows/language-updater.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  sync-files:
    name: "Run sync"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source repository"
        uses: actions/checkout@v4

      - name: "Run Language Manager"
        run: |
          chmod a+x ./LANGUAGE-MANAGER
          ./LANGUAGE-MANAGER

      - name: "Push to Source"
        run: |
          git config --global user.name "ivan-hc"
          git config --global user.email "noreply@github.com"
          git add LANGUAGE-MANAGER translations/*.po translations/usr
          if git diff-index --quiet HEAD; then
            echo "No changes to commit." >> $GITHUB_STEP_SUMMARY
          else
            git commit -m "Sync locale files"
            git push && echo "Sync locale files" >> $GITHUB_STEP_SUMMARY
          fi
